---
- name: Get rkt release from Github
  shell: "curl -L https://github.com/coreos/rkt/releases/download/v{{ rkt_version }}/rkt-v{{ rkt_version}}.tar.gz | tar xvf"

- name: Install the rkt binary
  file: 
    src: "rkt-v{{ rkt_version }}/rkt"
    dest: /usr/bin/rkt
    owner: root
    group: root
    mode: 0755
